[build]
  command = "flutter build web"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  FLUTTER_VERSION = "3.13.0"

[[plugins]]
  package = "@netlify/plugin-build"
